// modules.js - Mediencurriculum mit sprechenden Kompetenzbereichen
window.defaultCurriculumData = {
    5: [
        { id: "5_lese", name: "📖 5-Schritt-Lesemethode", dept: "LeKo", area: "lesekonzept", kmk: "basis", buildOn: null, notes: "Zentrales Element des Methodencurriculums zur Stärkung der Lesekompetenz im Schulverbund.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=7624235" }, 
        { id: "5_tab", name: "🍏 Grundlegende Bedienung des iPads ('Wischi wischi')", dept: "Allg.", area: "soziales", kmk: "basis", buildOn: null, notes: "Einführungskurs zur Gerätebedienung in den ersten Schulwochen.", linkDrive: null, linkMebis: null },
        { id: "5_scr", name: "🍏 Bildschirmkopien (Screenshots) aufnehmen und bearbeiten", dept: "Allg.", area: "soziales", kmk: "produzieren", buildOn: "5_tab", notes: "Grundlagentechnik zum Festhalten und Kommentieren von Bildschirminhalten.", linkDrive: null, linkMebis: null }, 
        { id: "5_bch", name: "🍏 Arbeit mit den digitalen Schulbüchern", dept: "Allg.", area: "soziales", kmk: "basis", buildOn: "5_tab", notes: "Freischaltung und Nutzung digitaler Schulbuch-Lizenzen im Unterricht.", linkDrive: null, linkMebis: null },
        { id: "5_ctrl", name: "🍏 Das Kontrollzentrum verwenden und anpassen", dept: "Allg.", area: "soziales", kmk: "basis", buildOn: "5_tab", notes: "Schnellzugriffe (Helligkeit, AirPlay, Timer) effizient einstellen.", linkDrive: null, linkMebis: null },
        { id: "5_rech", name: "📖 Recherche Buch 1: Altersgemäße Informationsbeschaffung", dept: "LeKo", area: "lesekonzept", kmk: "suchen", buildOn: "5_lese", notes: "Kombinierte Informationssuche in Bibliothek, Suchmaschinen und Online-Lexika.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=4713933" }, 
        { id: "5_pwd", name: "🍏 Verwendung des internen Passwort-Managers ('Schlüsselbund')", dept: "Allg.", area: "soziales", kmk: "basis", buildOn: "5_tab", notes: "Sichere Verwahrung schulinterner Zugangsdaten direkt auf dem Endgerät.", linkDrive: null, linkMebis: null },
        { id: "5_drive", name: "🟧 Arbeit mit ByCS Drive", dept: "Allg.", area: "soziales", kmk: "suchen", buildOn: "5_pwd", notes: "Nutzung des zentralen bayerischen Cloud-Speichers für den Dateiaustausch.", linkDrive: null, linkMebis: null },
        { id: "5_clip", name: "🍏 Arbeiten mit der Zwischenablage (z. B. Teilen-Dialog am iPad)", dept: "Allg.", area: "soziales", kmk: "kommunizieren", buildOn: "5_tab", notes: "Inhalte kopieren und flexibel via AirDrop oder Systemmenü weitergeben.", linkDrive: null, linkMebis: null },
        { id: "5_rsb", name: "🍏 Arbeit mit der Kommunikationsplattform RSBintern auf dem iPad", dept: "Allg.", area: "soziales", kmk: "kommunizieren", buildOn: "5_pwd", notes: "Umgang mit schulinternen Mails und Kommunikationskanälen.", linkDrive: null, linkMebis: null }, 
        { id: "5_bycs", name: "🟧 Arbeit mit ByCS Lernplattform auf dem iPad", dept: "Allg.", area: "soziales", kmk: "kommunizieren", buildOn: "5_pwd", notes: "Nutzung von mebis Kursstrukturen und Bearbeitung digitaler Aufgaben.", linkDrive: null, linkMebis: null },
        { id: "5_steck", name: "🖼 Steckbrief", dept: "Bio", area: "soziales", kmk: "produzieren", buildOn: "5_drive", notes: "Erstellung und Gestaltung eines biologischen Steckbriefs als erstes digitales Lernprodukt.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=3980830" }, 
        { id: "5_wand", name: "🖼 Wandzeitung", dept: "Mu", area: "soziales", kmk: "produzieren", buildOn: null, notes: "Mediale und visuelle Aufbereitung von Musikthemen im Team.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=3880847" },
        { id: "5_lap", name: "🖼 Lapbook", dept: "Geo", area: "soziales", kmk: "produzieren", buildOn: null, notes: "Kreative haptisch-digitale Synthese erarbeiteter geografischer Inhalte.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=4004065" },
        { id: "5_media", name: "🍏 Fotos, Screenshots, Videos aufnehmen, abspeichern und bearbeiten", dept: "Allg.", area: "soziales", kmk: "produzieren", buildOn: "5_scr", notes: "Erweiterte Medienbearbeitung (Zuschneiden, Markieren, Komprimieren).", linkDrive: null, linkMebis: null },
        { id: "5_copy", name: "Medienführerschein Bayern: Das ist meine Geschichte", dept: "IT", area: "soziales", kmk: "analysieren", buildOn: null, notes: "Grundlagen zum Schutz von geistigem Eigentum kennenlernen und verstehen.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/grundschule/3-und-4-jahrgangsstufe/das-ist-meine-geschichte" }
    ],
    6: [
        { id: "6_copy", name: "Medienführerschein Bayern: Das ist meine Geschichte", dept: "IT", area: "soziales", kmk: "analysieren", buildOn: null, notes: "Grundlagen zum Schutz von geistigem Eigentum kennenlernen und verstehen.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/grundschule/3-und-4-jahrgangsstufe/das-ist-meine-geschichte" }, 
        { id: "6_rech", name: "📖 Recherche Buch 2: Medien nutzen und gezielt verarbeiten", dept: "D", area: "lesekonzept", kmk: "suchen", buildOn: "5_rech", notes: "Vertiefte Informationsaufbereitung und -strukturierung aus Sachtexten.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=5810926" },
        { id: "6_www", name: "💻 Recherche WWW 1: Suchen mit kindgerechten Suchmaschinen", dept: "IT", area: "lesekonzept", kmk: "suchen", buildOn: "5_drive", notes: "Erste Schritte im World Wide Web mit gefilfteten, geschützten Suchportalen.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=5810923" }, 
        { id: "6_neti", name: "👬 Regelgerechtes Verhalten im Umgang miteinander (Netiquette)", dept: "Ku", area: "soziales", kmk: "kommunizieren", buildOn: "5_rsb", notes: "Erarbeitung von Richtlinien, Feedbackregeln und einer gesunden Chatkultur.", linkDrive: null, linkMebis: null },
        { id: "6_plak", name: "🖼 Plakat", dept: "M", area: "soziales", kmk: "produzieren", buildOn: null, notes: "Strukturierte Darstellung mathematischer/geometrischer Inhalte auf Postern.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=3880844" }, 
        { id: "6_flyer", name: "🖼 Flyer (einseitig)", dept: "G", area: "soziales", kmk: "produzieren", buildOn: "5_clip", notes: "Kompakte historische Zusammenfassungen zielgerichtet layouten und präsentieren.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=7607308" },
        { id: "6_vortrag", name: "🖼 Vortrag 1: Erstellen von Präsentationen und deren Bestandteilen", dept: "E", area: "soziales", kmk: "produzieren", buildOn: null, notes: "Erste digitale Folienstrukturen in der Fremdsprache aufbauen.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=3898460" }, 
        { id: "6_nonstop", name: "Medienführerschein Bayern: Medien non-stop?", dept: "Reli/Ethik", area: "soziales", kmk: "analysieren", buildOn: null, notes: "Die eigene Mediennutzung aktiv reflektieren, Bildschirmzeiten analysieren und Risiken erkennen.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/5-6-und-7-jahrgangsstufe/medien-non-stop" },
        { id: "6_ki", name: "🦾 Künstliche Intelligenz I – Sprachmodelle verstehen und anwenden", dept: "Allg.", area: "soziales", kmk: "basis", buildOn: "6_www", notes: "Grundlegendes Verständnis für generative KI und reflektierte Prompt-Eingaben.", linkDrive: "https://klickpunktschule.bycs.de/digitalkompass/startseite/ki-kompass/ki-kompass-5-8-uebersicht", linkMebis: "https://lernplattform.bycs.de/course/section.php?id=12663081" }
    ],
    7: [
        { id: "7_proj", name: "🖼 Erstellung von Projektdokumentationen unter Anwendung ausgewählter Programme", dept: "EG", area: "medien", kmk: "produzieren", buildOn: "6_flyer", notes: "Formale und funktionale Kriterien für strukturierte Berichte der Ausbildungszweige IIIa und Ernährung und Gesundheit.", linkDrive: null, linkMebis: null }, 
        { id: "7_www2", name: "💻 Recherche WWW 2: kritisches Filtern & eigenständiges Suchen", dept: "Geo", area: "lesekonzept", kmk: "suchen", buildOn: "6_www", notes: "Lehrplanbereich IT 1.4. Vertiefte Filterung von Internet-Ergebnissen und eigenständige Recherchestrategien im Fach Geographie.", linkDrive: null, linkMebis: null },
        { id: "7_soc", name: "👬 Verantwortungsvolle Nutzung von Social Media", dept: "IT", area: "medien", kmk: "kommunizieren", buildOn: "6_neti", notes: "Etablierung fächerübergreifender Kommunikationsregeln, Feedbackprozesse und nachhaltiger Verhaltensweisen im Netz.", linkDrive: null, linkMebis: null },
        { id: "7_audio", name: "🖼 Audioprodukte", dept: "E", area: "medien", kmk: "produzieren", buildOn: null, notes: "Kreative Synthese fächerübergreifender Inhalte durch eigene Audio-Aufnahmen, Podcasts oder Dialogsequenzen.", linkDrive: null, linkMebis: null },
        { id: "7_fake", name: "Medienführerschein Bayern: Fakt oder Fake? Glaubwürdigkeit von Online-Quellen prüfen und bewerten", dept: "Allg.", area: "medien", kmk: "analysieren", buildOn: "7_www2", notes: "Kritisches Instrumentarium zum Entlarven manipulativer Netzinhalte, Deepfakes und Falschmeldungen.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/5-6-und-7-jahrgangsstufe/fakt-oder-fake" },
        { id: "7_netz1", name: "Medienführerschein Bayern: Ich im Netz I – Inhalte in Social-Media-Angeboten reflektieren und bewerten", dept: "Ku", area: "medien", kmk: "analysieren", buildOn: "7_soc", notes: "Visuelle Selbstdarstellung auf Online-Plattformen und bewusster Umgang mit Likes und Trends.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/5-6-und-7-jahrgangsstufe/ich-im-netz-i" },
        { id: "7_mob", name: "Medienführerschein Bayern: Ich im Netz II – Cyber-Mobbing in Social-Media-Angeboten thematisieren und vorbeugen", dept: "IT", area: "medien", kmk: "basis", buildOn: "7_soc", notes: "Präventionsstrategien zur Deeskalation, rechtliche Grauzonen und aktive Hilfestellungen im Ernstfall im Verbundprojekt.", linkDrive: null, linkMebis: null },
        { id: "7_mob_ref", name: "Medienführerschein Bayern: Ich im Netz II – Cyber-Mobbing in Social-Media-Angeboten thematisieren und vorbeugen", dept: "IT", area: "medien", kmk: "basis", buildOn: "7_soc", notes: "Präventionsstrategien zur Deeskalation, rechtliche Grauzonen und aktive Hilfestellungen im Ernstfall im Verbundprojekt.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/5-6-und-7-jahrgangsstufe/ich-im-netz-ii" }
    ],
    8: [
        { id: "8_proj_doc", name: "🖼 Erstellung von Projektdokumentationen", dept: "Projekt", area: "verantwortung", kmk: "produzieren", buildOn: "7_proj", notes: "Methodische Ausarbeitung von Projektberichten als Kernvorbereitung auf die Projektprüfung.", linkDrive: null, linkMebis: null },
        { id: "8_search_strat", name: "💻 Suchstrategien entwickeln", dept: "Projekt", area: "verantwortung", kmk: "suchen", buildOn: "7_www2", notes: "Gezielte Informationsbeschaffung und Analyse für die eigenständige Themenerarbeitung.", linkDrive: null, linkMebis: null },
        { id: "8_mediascouts", name: "👬 Erworbene Kompetenzen weitergeben und anwenden", dept: "Allg.", area: "verantwortung", kmk: "kommunizieren", buildOn: null, notes: "Aktiver Wissenstransfer in der Schulgemeinschaft (z. B. durch die AG Medienscouts).", linkDrive: null, linkMebis: null },
        { id: "8_portfolio", name: "🖼 Portfolio", dept: "IT", area: "verantwortung", kmk: "produzieren", buildOn: null, notes: "Digitale Dokumentation und Reflexion des eigenen Lernfortschritts im Fach Informationstechnologie.", linkDrive: null, linkMebis: "https://lernplattform.bycs.de/course/section.php?id=4287591" },
        { id: "8_public", name: "🖼 Präsentation und Publikation für die Öffentlichkeit", dept: "Allg.", area: "verantwortung", kmk: "produzieren", buildOn: null, notes: "Aufbereitung von Unterrichtsinhalten für Webseite, One-Pager, Podcast, Jahresbericht oder Schülerzeitung.", linkDrive: null, linkMebis: null },
        { id: "8_urheber", name: "Medienführerschein Bayern: Ich als Urheber", dept: "Ch", area: "verantwortung", kmk: "analysieren", buildOn: null, notes: "Urheberrechte im Netz kennen, reflektieren und geistiges Eigentum respektieren.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/8-9-und-10-jahrgangsstufe/ich-als-urheber" },
        { id: "8_recht_netz", name: "Medienführerschein Bayern: Ich im Netz III", dept: "WR", area: "verantwortung", kmk: "basis", buildOn: null, notes: "Rechtliche Grundlagen digitaler Interaktionen kennenlernen, verstehen und reflektieren.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/8-9-und-10-jahrgangsstufe/ich-als-urheber" }
    ],
    9: [
        { id: "9_voll", name: "Vollständige Projektdokumentation", dept: "IT", area: "verantwortung", kmk: "produzieren", buildOn: "8_portfolio", notes: "Abschlussberichte und Prüfungsrelevanz.", linkDrive: null, linkMebis: null }, 
        { id: "9_port", name: "Portfolio (Individuelle Lernprodukte)", dept: "Allg.", area: "verantwortung", kmk: "produzieren", buildOn: "8_portfolio", notes: "Digitale Kompetenzmappe.", linkDrive: null, linkMebis: null }
    ],
    10: [
        { id: "10_games", name: "Medienführerschein Bayern: Generation Games?", dept: "IT", area: "verantwortung", kmk: "analysieren", buildOn: "6_nonstop", notes: "Digitale Spiele im Abschlussjahr gezielt diskutieren, Spielverhalten reflektieren und Suchtfaktoren analysieren.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/8-9-und-10-jahrgangsstufe/generation-games" }, 
        { id: "10_dschungel", name: "Medienführerschein Bayern: Im Informationsdschungel", dept: "PuG", area: "verantwortung", kmk: "analysieren", buildOn: null, notes: "Meinungsbildungsprozesse verstehen, Medieneinflüsse hinterfragen, Filterblasen und Algorithmen entlarven.", linkDrive: null, linkMebis: "https://www.medienfuehrerschein.bayern/angebot/schule/weiterfuehrende-schulen/8-9-und-10-jahrgangsstufe/im-informationsdschungel" }
    ]
};